version: '3.3'

services:
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --sauthentication_policy=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: sokoban
   MYSQL_DATABASE: sokoban
   MYSQL_USER: root
   MYSQL_PASSWORD: root
  ports:
   - 3306:3306
  volumes:
   - ./data/db:/var/lib/mysql
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: root
   PMA_PASSWORD: root
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80